//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbValue
    {
        public int Id { get; set; }
        public int VariableId { get; set; }
        public int Index { get; set; }
        public string Value { get; set; }
    
        public virtual DbVariable Variable { get; set; }
    }
}
