//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbVariable
    {
        public DbVariable()
        {
            this.Values = new HashSet<DbValue>();
        }
    
        public int Id { get; set; }
        public int DataSetId { get; set; }
        public string Name { get; set; }
        public string VarType { get; set; }
        public bool IsCateg { get; set; }
        public bool IsId { get; set; }
        public bool IsName { get; set; }
        public string Description { get; set; }
        public bool IsImageVar { get; set; }
        public bool IsInfoVar { get; set; }
    
        public virtual DbDataSet DataSet { get; set; }
        public virtual ICollection<DbValue> Values { get; set; }
    }
}
