//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class statdataEntities : DbContext
    {
        public statdataEntities()
            : base("name=statdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DbDataSet> DbDataSets { get; set; }
        public DbSet<DbKey> DbKeys { get; set; }
        public DbSet<DbValue> DbValues { get; set; }
        public DbSet<DbVariable> DbVariables { get; set; }
        public DbSet<DbPhoto> DbPhotoes { get; set; }
    }
}
